apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "RootP@ss123"
  MYSQL_DATABASE: "lampdb"
  MYSQL_USER: "lampuser"
  MYSQL_PASSWORD: "LampP@ss123"
